export const dummyImg = [
  {name: 'a', img: 'https://picsum.photos/200'},
  {name: 'b', img: 'https://picsum.photos/200'},
  {name: 'c', img: 'https://picsum.photos/200'},
  {name: 'd', img: 'https://picsum.photos/200'},
  {name: 'e', img: 'https://picsum.photos/200'},
  {name: 'f', img: 'https://picsum.photos/200'},
  {name: 'g', img: 'https://picsum.photos/200'},
  {name: 'h', img: 'https://picsum.photos/200'},
  {name: 'i', img: 'https://picsum.photos/200'},
  {name: 'j', img: 'https://picsum.photos/200'},
  {name: 'k', img: 'https://picsum.photos/200'},
  {name: 'l', img: 'https://picsum.photos/200'},
  {name: 'm', img: 'https://picsum.photos/200'},
  {name: 'n', img: 'https://picsum.photos/200'},
  {name: 'o', img: 'https://picsum.photos/200'},
  {name: 'p', img: 'https://picsum.photos/200'},
  {name: 'q', img: 'https://picsum.photos/200'},
  {name: 'r', img: 'https://picsum.photos/200'},
  {name: 's', img: 'https://picsum.photos/200'},
  {name: 't', img: 'https://picsum.photos/200'},
];